a=int(input("Numarul de oua de la prima gaina in aceasts saptamana:"))
b=int(input("Numarul de oua de la a doua gaina in aceasts saptamana:"))
c=int(input("Numarul de oua de la a treia gaina in aceasts saptamana:"))
d=int(input("Numarul de oua de la a patra gaina in aceasts saptamana:"))
print ("Numarul de oua in aceasta saptamana: ",a+b+c+d)
