a=int(input("Numarul de oua de la prima gaina in aceasta saptamana:"))
b=int(input("Numarul de oua de la a doua gaina in aceasta saptamana:"))
c=int(input("Numarul de oua de la a treia gaina in aceasta saptamana:"))
d=int(input("Numarul de oua de la a patra gaina in aceasta saptamana:"))
print ("Numarul de oua in aceasta saptamana: ",a+b+c+d)
